== Manual steps
Following manual steps need to be performed before deploying OpenStack on the platform:

0. Build deployment containers.
TODO: Add commands for starting deployment containers with all necessary volumes mounted.
1. Spin up the Heat stack with all the instances. Wait for it to complete creating all resources.
2. Generate inventory hosts.

-------
# /etc/kolla/scripts/generate_inventory.py /etc/kolla/inventory/vkolla/01_hosts
-------
3. Log into the VPN deployment container and install OpenVPN on the bastion host:

-------
# cd ~/vpn-deploy/
# ansible -i /etc/kolla/inventory/vkolla all -m raw -a "apt-get update; apt-get -y install python-dev"
# ansible-playbook -i /etc/kolla/inventory/vkolla vpn-deploy.yml -e 'target=bastions'
-------
5. Bring secondary interfaces up:

-------
# ansible -i /etc/kolla/inventory/vkolla control,network,compute -m raw -a "ip link set ens4 up"
# ansible -i /etc/kolla/inventory/vkolla control,network,compute -m raw -a "dhclient -v ens4"
# ansible -i /etc/kolla/inventory/vkolla network -m raw -a "ip link set ens5 up"
# ansible -i /etc/kolla/inventory/vkolla network -m raw -a "ip link set ens6 up"
# ansible -i /etc/kolla/inventory/vkolla network -m raw -a "dhclient -v ens6"
-------
6. Bootstrap servers to install prerequisites, create config directories, etc.

-------
# cd /kolla/kolla-ansible/tools/
# ./kolla-ansible -i /etc/kolla/inventory/vkolla bootstrap-servers
-------
7. Deploy Ceph with `ceph-ansible`:

-------
# mkdir /ceph
# git clone https://github.com/ceph/ceph-ansible -b stable-3.1 /ceph/ceph-ansible/
# cd /ceph/ceph-ansible/
# cp site.yml.sample site.yml
# echo "control_path = /dev/shm/cp%%h-%%p-%%r" >> ansible.cfg
# ansible-playbook -i /etc/kolla/inventory/ceph site.yml
-------
8. Download Ceph config file and client keys for services utilising Ceph:

-------
# ansible-playbook -i /etc/kolla/inventory/ceph /etc/kolla/playbooks/fetch_ceph_config_and_keys.yml
-------
9. Deploy Kolla with Kolla-Ansible:

-------
# cd /kolla/kolla-ansible/tools/
# ./kolla-ansible -i /etc/kolla/inventory/vkolla deploy
-------
10. Post deploy, testing, etc.

-------
# ./kolla-ansible -i /etc/kolla/inventory/vkolla post-deploy
# source /etc/kolla/admin-openrc.sh
# /etc/kolla/scripts/populate_dev_cloud.sh
-------

=== Client instance
Deployment stack also creates a small client instance that can access deployment through the external VIP and has openstack CLI tools installed.

To use this client, you'll also need admin password, so get it by running this command on the deployment container:

-------
# grep keystone_admin /etc/kolla/passwords.yml
-------
Next, find the IP of the `test_client` instance and log into it (as `ubuntu` user). When inside, source environment variables from this openrc file:

-------
$ source admin-openrc.sh
-------
Run some openstack client commands -- like `openstack image list`, `nova list` -- to confirm this works as expected.

== Custom overrides
To enable a service that's not part of the current config, first add groupings for this service (as a new file) in the inventory:

-------
# cat /etc/kolla/inventory/vkolla/90_heat
[heat:children]
control

[heat-api:children]
heat

[heat-api-cfn:children]
heat

[heat-engine:children]
heat
-------
Next, apply your overrides - here Heat is enabled:

-------
# cat /etc/kolla/globals_heat.yml
---
enable_heat: "yes"
-------
Finally, rerun `deploy` playbooks with your overrides as extra vars (use tags to speed up the process if the platform has already been deployed):

-------
# cd /kolla/kolla-ansible/tools/
# ./kolla-ansible -i /etc/kolla/inventory/vkolla deploy -e @/etc/kolla/globals_heat.yml --tags haproxy,heat
-------
