== Manual steps
Following manual steps need to be performed before deploying OpenStack on the platform:

* Clone prerequisites:
-------
$ mkdir reqs
$ cd reqs/
$ git clone https://github.com/mkarpiarz/vkolla-deploy
$ cd vkolla-deploy/
$ git checkout 7d55ae2d7aa4989e9a7c6b6b37a654c74a930d56
$ cd ..
$ git clone https://github.com/mkarpiarz/vpn-deploy
$ cd vpn-deploy/
$ git checkout 268948d4de1353b6c81aefce20e48f417846866a
$ cd -
$ git clone https://github.com/ceph/ceph-ansible -b stable-3.1
-------

* On a machine with Docker (laptop, server) build a deployment container image using the Dockerfile in `reqs/vkolla-deploy/` repo by running the following commands:
+
-------
$ cd reqs/vkolla-deploy/
$ docker build . \
    --build-arg K_BRANCH=${K_BRANCH} \
    --build-arg KA_BRANCH=${KA_BRANCH} \
    --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION} \
    -t kolla-deploy:latest
-------
where build-args can be set to the following (tested) values:
+
*OPENSTACK TRAIN:*
+
** `export K_BRANCH="stable/train"`
** `export KA_BRANCH="stable/train"`
** `export ANSIBLE_VERSION=2.8.7`
+
*(old) OPENSTACK QUEENS:*
+
** `export K_BRANCH="stable/queens"`
** `export KA_BRANCH="stable/queens"`
** `export ANSIBLE_VERSION=2.4`
+
* Run the deployment container:
+
-------
docker run -dit --name kolla-deploy \
    -v $(pwd):/etc/kolla/ \
    -v $(pwd)/reqs/ceph-ansible/:/ceph/ceph-ansible/ \
    -v $(pwd)/reqs/vpn-deploy/:/vpn-deploy/ \
    -v <VPN-conf-dir>:/root/VPN/ \
    -v <hostdir-for-root-homedir>:/root/ \
    kolla-deploy:latest \
    /bin/bash
-------
where `<VPN-conf-dir>` is host a directory where VPN client config and keys for accessing private networks will be downloaded (doesn't need to exist) and `<root-homedir-with-ssh-keys>` is a directory for storing container's `/root` persistently on the host.
+
[NOTE]
=======
Named volumes can be used instead of host directories.
=======
+
* Transfer your OpenStack openrc file to the container using, for example, `docker cp`:
+
-------
$ docker cp <your-openrc-file> kolla-deploy:/openrc
-------
+
* Log into the container:
+
-------
$ docker exec -it kolla-deploy /bin/bash
-------
+
* Generate SSH keys for the container and add them to Keystone:
+
-------
# ssh-keygen -t rsa -f ~/.ssh/id_rsa
# source /openrc
# openstack keypair create --public-key ~/.ssh/id_rsa.pub <your-keypair-name>
-------
Replace `<your-keypair-name>` with the name you want for your keypair to have in OpenStack.
+
* Spin up Heat stack with all the resources:
+
-------
# source /openrc
# cd /etc/kolla/heat/
# openstack stack create --template vkolla-stack.yml --parameter key=<your-keypair-name> vkolla --wait
-------
+
[NOTE]
=======
If you want to override default parameters of this Heat stack template, you can do so in a separate yaml (see existing `env_*.yml` files in the directory with the template) and then pass the name of this yaml with the `--environment` flag when running `openstack stack create`.
=======
+
* Generate inventory hosts.
+
-------
# /etc/kolla/scripts/generate_inventory.py /etc/kolla/inventory/vkolla/01_hosts
-------
+
* Install Python on the bastion:
+
-------
# ansible -i /etc/kolla/inventory/vkolla bastions -m raw -a "apt-get update; apt-get -y install python-dev"
-------
+
* Install OpenVPN on the bastion host:
+
-------
# cd /vpn-deploy/
# ansible-galaxy install -r requirements.yml
# ansible-playbook -i /etc/kolla/inventory/vkolla vpn-deploy.yml -e 'target=bastions'
-------
+
[NOTE]
=======
By default this playbook sets up OpenVPN so that all your traffic goes through the tunnel. If this is not what you want, add `-e 'openvpn_redirect_gateway=false'` to the last command. If you're doing this, remember to add (on your client host) a static route so that traffic directed to internal networks of the deployment goes though the tunnel device, for example: `ip route add 192.168.17.0/24 dev tun0`.
=======
+
* From now on private IPs of instances will be used, so add fetched client config and keys (available in the `/root/VPN/` directory inside the container or in the respective hostdir) to your VPN client (openvpn, Tunnelblick, Viscosity, ...) and activate the tunnel.
+
* Install Python on all hosts:
+
-------
# ansible -i /etc/kolla/inventory/vkolla all -m raw -a "apt-get update; apt-get -y install python-dev"
-------
+
* Bring secondary interfaces up:
+
-------
# ansible -i /etc/kolla/inventory/vkolla control,network,compute -m raw -a "ip link set ens4 up"
# ansible -i /etc/kolla/inventory/vkolla control,network,compute -m raw -a "dhclient -v ens4"
# ansible -i /etc/kolla/inventory/vkolla network -m raw -a "ip link set ens5 up"
# ansible -i /etc/kolla/inventory/vkolla network -m raw -a "ip link set ens6 up"
# ansible -i /etc/kolla/inventory/vkolla network -m raw -a "dhclient -v ens6"
-------
+
* Deploy Ceph with `ceph-ansible`:
+
-------
# cd /ceph/ceph-ansible/
# cp site.yml.sample site.yml
# echo "control_path = /dev/shm/cp%%h-%%p-%%r" >> ansible.cfg
# ansible-playbook -i /etc/kolla/inventory/ceph site.yml
-------
+
* Download Ceph config file and client keys for services utilising Ceph:
+
-------
# ansible-playbook -i /etc/kolla/inventory/ceph /etc/kolla/playbooks/fetch_ceph_config_and_keys.yml
-------
+
* Generate passwords for components of the deployment:
+
-------
# cd /kolla/kolla-ansible/
# cp etc/kolla/passwords.yml /etc/kolla/passwords.yml
# ./tools/generate_passwords.py
-------
+
* Bootstrap servers to install prerequisites, create config directories, etc.
+
-------
# cd /kolla/kolla-ansible/tools/
# ./kolla-ansible -i /etc/kolla/inventory/vkolla bootstrap-servers
-------
+
* Deploy Kolla with Kolla-Ansible:
+
-------
# cd /kolla/kolla-ansible/tools/
# ./kolla-ansible -i /etc/kolla/inventory/vkolla deploy
-------
+
* Post deploy, testing, etc.
+
-------
# ./kolla-ansible -i /etc/kolla/inventory/vkolla post-deploy
# source /etc/kolla/admin-openrc.sh
# /etc/kolla/scripts/populate_dev_cloud.sh
-------

[NOTE]
=======
To route traffic in and out instances launched on this platform (this includes communicating with them through their floating IPs), port security must be disabled on ports in the network serving as provider network on the underlying cloud platform. Currently this is a manual process that can be done in Horizon by first removing all security groups from all named ports in the `provider_net` network and then unchecking the "Port Security" checkbox.
=======

=== Client instance
Deployment stack also creates a small client instance that can access deployment through the external VIP and has openstack CLI tools installed.

To use this client, you'll also need admin password, so get it by running this command on the deployment container:

-------
# grep keystone_admin /etc/kolla/passwords.yml
-------
Next, find the IP of the `test_client` instance and log into it (as `ubuntu` user). When inside, source environment variables from this openrc file:

-------
$ source admin-openrc.sh
-------
Run some openstack client commands -- like `openstack image list`, `nova list` -- to confirm this works as expected.

[NOTE]
=======
You can also SSH into launched VMs through their floating IPs from this client instance.
=======

== Custom overrides
To enable a service that's not part of the current config, first add groupings for this service (as a new file) in the inventory:

-------
# cat /etc/kolla/inventory/vkolla/90_heat
[heat:children]
control

[heat-api:children]
heat

[heat-api-cfn:children]
heat

[heat-engine:children]
heat
-------
Next, apply your overrides - here Heat is enabled:

-------
# cat /etc/kolla/globals_heat.yml
---
enable_heat: "yes"
-------
Finally, rerun `deploy` playbooks with your overrides as extra vars (use tags to speed up the process if the platform has already been deployed):

-------
# cd /kolla/kolla-ansible/tools/
# ./kolla-ansible -i /etc/kolla/inventory/vkolla deploy -e @/etc/kolla/globals_heat.yml --tags haproxy,heat
-------

If you want to deploy the service to only a subset of nodes within a group or across multiple groups, then instead of adding groupings to the inventory, add them to the `groups` metadata tag. For example with this metadata:

-------
metadata:
  groups: control,heat,heat-api,heat-api-cfn,heat-engine
-------
you can install all Heat components on a selected control node.

[NOTE]
=======
Currently, nothing is taking care of opening ports for services enabled this way, so appropriate security group rules need to be added separately.
=======

[WARNING]
=======
The default control node flavour with 4GB of RAM is just enough for essential services (infra + Keystone + Glance + Nova + Neutron) -- adding any more may result in those instances going OOM which in turn can lead to database containers crushing. Use flavours with more RAM if you plan on enabling extra services.
Run `./kolla-ansible` with `mariadb_recovery` to fix the database if it happened to break.
=======

== Known issues

* Tasks like "Running Neutron bootstrap container" can run for a long time. If this time is longer than SSH connection timeout for deployment hosts, the whole deployment will fail. The bootstrap process will still continue, so deployment playbooks can be safely rerun when this is done. TODO: Increase this timeout?
