heat_template_version: 2017-09-01

description: Multinode OpenStack deployment with Kolla and vScaller

parameters:
  image:
    type: string
    label: Instance image
    description: Image to use for instances
    default: Ubuntu-16.04-LTS
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for access to instances
  control_flavour:
    type: string
    label: Control instance flavour
    description: Flavour to use with control instances
    default: m1.medium
  network_flavour:
    type: string
    label: Network instance flavour
    description: Flavour to use with network instances
    default: m1.medium
  compute_flavour:
    type: string
    label: Compute instance flavour
    description: Flavour to use with compute instances
    default: m1.large
  client_flavour:
    type: string
    label: Client instance flavour
    description: Flavour to use with client instances
    default: m1.small
  main_net:
    type: string
    label: Main network
    description: Main internal network
    default: private

resources:
  os_services_infra_client:
    type: OS::Neutron::SecurityGroup
    properties:
      description: SecGroup to assign to hosts requiring access to infrastructure services
      name: os-services-infra-client
      rules: []

  os_services_infra_server:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Open ports for infrastructure services
      name: os-services-infra-server

  rabbitmq_main_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_infra_server }
      description: RabbitMQ main port
      direction: ingress
      port_range_min: 5672
      port_range_max: 5672
      protocol: tcp
      remote_group: { get_resource: os_services_infra_client }
  rabbitmq_mgmt_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_infra_server }
      description: RabbitMQ Management console
      direction: ingress
      port_range_min: 15672
      port_range_max: 15672
      protocol: tcp
      remote_group: { get_resource: os_services_infra_client }
  rabbitmq_cluster_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_infra_server }
      description: RabbitMQ cluster
      direction: ingress
      port_range_min: 25672
      port_range_max: 25672
      protocol: tcp
      remote_group: { get_resource: os_services_infra_client }

  mysql_main_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_infra_server }
      description: MySQL/MariaDB main port
      direction: ingress
      port_range_min: 3306
      port_range_max: 3306
      protocol: tcp
      remote_group: { get_resource: os_services_infra_client }
  mysql_repl_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_infra_server }
      description: MySQL/MariaDB replication port (Galera)
      direction: ingress
      port_range_min: 4567
      port_range_max: 4567
      protocol: tcp
      remote_group: { get_resource: os_services_infra_client }

  memcached_main_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_infra_server }
      description: Memcached main port
      direction: ingress
      port_range_min: 11211
      port_range_max: 11211
      protocol: tcp
      remote_group: { get_resource: os_services_infra_client }

  haproxy_stats_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_infra_server }
      description: HAProxy statistics report
      direction: ingress
      port_range_min: 1984
      port_range_max: 1984
      protocol: tcp
      remote_group: { get_resource: os_services_infra_client }

  os_services_api_client:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Assign to hosts requiring access to OpenStack APIs
      name: os-services-api-client
      rules: []

  os_services_api_server:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Open ports for OpenStack APIs
      name: os-services-api-server

  keystone_public_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_api_server }
      description: Keystone public endpoint
      direction: ingress
      port_range_min: 5000
      port_range_max: 5000
      protocol: tcp
      remote_group: { get_resource: os_services_api_client }
  keystone_admin_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_api_server }
      description: Keystone admin endpoint
      direction: ingress
      port_range_min: 35357
      port_range_max: 35357
      protocol: tcp
      remote_group: { get_resource: os_services_api_client }

  glance_api_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_api_server }
      description: Glance API
      direction: ingress
      port_range_min: 9292
      port_range_max: 9292
      protocol: tcp
      remote_group: { get_resource: os_services_api_client }
  glance_registry_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_api_server }
      description: Glance registry
      direction: ingress
      port_range_min: 9191
      port_range_max: 9191
      protocol: tcp
      remote_group: { get_resource: os_services_api_client }

  neutron_server_port:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: os_services_api_server }
      description: Neutron server API
      direction: ingress
      port_range_min: 9696
      port_range_max: 9696
      protocol: tcp
      remote_group: { get_resource: os_services_api_client }

  control_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: control_flavour }
      key_name: { get_param: key }
      security_groups:
        - { get_resource: os_services_infra_server }
        - { get_resource: os_services_api_server }
      networks:
        - network: { get_param: main_net }

  # TODO: Use `allowed_address_pairs` instead of disabling port security.
  # TODO: Allow access to HAProxy stats.
  network_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: network_flavour }
      key_name: { get_param: key }
      security_groups:
        - { get_resource: os_services_infra_server }
        - { get_resource: os_services_infra_client }
        - { get_resource: os_services_api_server }
        - { get_resource: os_services_api_client }
      networks: [{
          network: { get_param: main_net },
          port_extra_properties: {
            port_security_enabled: false
          }
        }
      ]

  compute_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: compute_flavour }
      key_name: { get_param: key }
      security_groups:
        - { get_resource: os_services_infra_client }
        - { get_resource: os_services_api_client }
      networks:
        - network: { get_param: main_net }

  test_client:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: client_flavour }
      key_name: { get_param: key }
      security_groups:
        - { get_resource: os_services_infra_client }
        - { get_resource: os_services_api_client }
      networks:
        - network: { get_param: main_net }
